name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "Linting ..."

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Testing ..."

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Build
        run: echo "Building ..."

  security-check:
    name: The PHP Security Checker
    runs-on: ubuntu-lates
    steps:
      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v4

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}

      - name: Run PHP code
        shell: php {0}
        run: |
          <?php
          $welcome = "Hello, world";
          echo $welcome;
